server:
  port: 8082

spring:
  application:
    name: absence-management
  datasource:
    url: jdbc:mysql://localhost:3306/absence_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    secure-port-enabled: true
    secure-port: 8082 
    status-page-url: https://localhost:8082/actuator/info
    health-check-url: https://localhost:8082/actuator/health
    home-page-url: https://localhost:8082/
jwt:
  secret: my-shared-service-secret-key
