 port: 8443
    ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: 1
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**
          filters:
            - name: JwtValidation
              args:
                secret: ${jwt.secret}
        - id: absence-management
          uri: lb://absence-management
          predicates:
            - Path=/api/absence/**
          filters:
            - name: JwtValidation
        - id: employee-profile
          uri: lb://employee-profile
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET:my-shared-service-secret-key} 

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
