server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:gateway-keystore.p12
    key-store-password: mypassword
    key-store-type: PKCS12

    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
  http2:
    enabled: true
  tls:
    enabled: true


spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**
        - id: absence-management
          uri: lb://absence-management
          predicates:
            - Path=/api/absence/**
        - id: employee-profile
          uri: lb://employee-profile
          predicates:
            - Path=/employee-profile/**
    discovery:
      enabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8081/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
