server:
  port: 8443
    ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: 1
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
        - id: payroll-service
          uri: https://localhost:8083
          predicates:
            - Path=/api/payroll/**
        - id: absence-management
          uri: https://localhost:8082
          predicates:
            - Path=/api/absence/**
        - id: employee-profile
          uri: lb://employee-profile
          predicates:
            - Path=/employee-profile/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    secure-port: 8443
    status-page-url: https://localhost:8443/actuator/info
    health-check-url: https://localhost:8443/actuator/health
    home-page-url: https://localhost:8443/
jwt:
  secret: my-shared-service-secret-key
