server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: secure-localhost 
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**
        - id: absence-management
          uri: lb://absence-management
          predicates:
            - Path=/api/absence/**
        - id: employee-profile
          uri: lb://employee-profile
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=api/auth/(?<segment>.*), /app/${segment}

jwt:
  secret: "maCleSecreteTrèsLonguePourJWTQueTuDoisChangerEtMettreEnSecurite123!"

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
