server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:gateway-keystore.p12
    key-store-password: mypassword
    key-store-type: PKCS12
  http2:
    enabled: true

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**
        - id: absence-management
          uri: lb://absence-management
          predicates:
            - Path=/api/absence/**
        - id: employee-profile
          uri: lb://employee-profile
          predicates:
            - Path=/employee-profile/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
