server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**
        - id: absence-management
          uri: lb://absence-management
          predicates:
            - Path=/api/absence/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
