server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12

spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:mysql://localhost:3306/payroll_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    secure-port-enabled: true
    secure-port: 8083
    status-page-url: https://localhost:8083/actuator/info
    health-check-url: https://localhost:8083/actuator/health

jwt:
  secret: dev-secret-key-123
