server:
  port: 8083

spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:mysql://localhost:3306/payroll_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    secure-port-enabled: true
    secure-port: 8083  
    status-page-url: https://localhost:8083/actuator/info
    health-check-url: https://localhost:8083/actuator/health
    home-page-url: https://localhost:8083/
